# Gathering data (memanggil data)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Tabel data covid
data_covid=pd.read_csv("/content/covid-19-indonesia.csv")
data_covid.head()

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.0,1.0
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.0,1.0

# Statistik Deskriptif

# Data assessing

In [ ]:
# menilai data
data_covid.info()
data_covid.isna().sum()
print("Jumlah duplikasi: ", data_covid.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18002 entries, 0 to 18001
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         18002 non-null  object
 1   Location ISO Code            18002 non-null  object
 2   Location                     18002 non-null  object
 3   New Cases                    18002 non-null  int64
 4   New Deaths                   18002 non-null  int64
 5   New Recovered                18002 non-null  int64
 6   New Active Cases             18002 non-null  int64
 7   Total Cases                  18002 non-null  int64
 8   Total Deaths                 18002 non-null  int64
 9   Total Recovered              18002 non-null  int64
 10  Total Active Cases           18002 non-null  int64
 11  Location Level               18002 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     17469 non-null  object
 14  Country                      18002 non-null  object
 15  Continent                    18002 non-null  object
 16  Island                       17469 non-null  object
 17  Time Zone                    17469 non-null  object
 18  Special Status               2584 non-null   object
 19  Total Regencies              18002 non-null  int64
 20  Total Cities                 17495 non-null  float64
 21  Total Districts              18002 non-null  int64
 22  Total Urban Villages         17492 non-null  float64
 23  Total Rural Villages         17468 non-null  float64
 24  Area (km2)                   18002 non-null  int64
 25  Population                   18002 non-null  int64
 26  Population Density           18002 non-null  float64
 27  Longitude                    18002 non-null  float64
 28  Latitude                     18001 non-null  float64
 29  New Cases per Million        18001 non-null  float64
 30  Total Cases per Million      18001 non-null  float64
 31  New Deaths per Million       18001 non-null  float64
 32  Total Deaths per Million     18001 non-null  float64
 33  Total Deaths per 100rb       18001 non-null  float64
 34  Case Fatality Rate           18001 non-null  object
 35  Case Recovered Rate          18001 non-null  object
 36  Growth Factor of New Cases   16938 non-null  float64
 37  Growth Factor of New Deaths  15911 non-null  float64
dtypes: float64(14), int64(12), object(12)
memory usage: 5.2+ MB
Jumlah duplikasi:  0

# Data Cleaning

In [ ]:
# Menghapus Variabel yang tidak diperlukan
data_covid=data_covid.drop(['City or Regency','Time Zone','Special Status'], axis=1)
data_covid.head()

In [ ]:
# mengatasi missing value
data_covid=data_covid.rename(columns={'Total Cities':'Total_Cities','Total Urban Villages':'Total_Urban', 'Total Rural Villages':'Total_Rural'})
# kolom Province
data_covid.Province.fillna(value="Indonesia", inplace=True)
# kolom Island
data_covid.Island.fillna(value="Indonesia", inplace=True)
# Kolom Total Cities
data_covid.Total_Cities.fillna(value=data_covid.Total_Cities.median(), inplace=True)
# Kolom Total Urban Villages
data_covid.Total_Urban.fillna(value=data_covid.Total_Urban.median(), inplace=True)
# Kolom Total Rural Villages
data_covid.Total_Rural.fillna(value=data_covid.Total_Rural.median(), inplace=True)

In [ ]:
# mengatasi kesalahan tipe data
# Kolom Date
datetime_columns=["Date"]
for column in datetime_columns :
  data_covid[column]=pd.to_datetime(data_covid[column])
data_covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18002 entries, 0 to 18001
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         18002 non-null  datetime64[ns]
 1   Location ISO Code            18002 non-null  object
 2   Location                     18002 non-null  object
 3   New Cases                    18002 non-null  int64
 4   New Deaths                   18002 non-null  int64
 5   New Recovered                18002 non-null  int64
 6   New Active Cases             18002 non-null  int64
 7   Total Cases                  18002 non-null  int64
 8   Total Deaths                 18002 non-null  int64
 9   Total Recovered              18002 non-null  int64
 10  Total Active Cases           18002 non-null  int64
 11  Location Level               18002 non-null  object
 12  Province                     18002 non-null  object
 13  Country                      18002 non-null  object
 14  Continent                    18002 non-null  object
 15  Island                       18002 non-null  object
 16  Total Regencies              18002 non-null  int64
 17  Total_Cities                 18002 non-null  float64
 18  Total Districts              18002 non-null  int64
 19  Total_Urban                  18002 non-null  float64
 20  Total_Rural                  18002 non-null  float64
 21  Area (km2)                   18002 non-null  int64
 22  Population                   18002 non-null  int64
 23  Population Density           18002 non-null  float64
 24  Longitude                    18002 non-null  float64
 25  Latitude                     18001 non-null  float64
 26  New Cases per Million        18001 non-null  float64
 27  Total Cases per Million      18001 non-null  float64
 28  New Deaths per Million       18001 non-null  float64
 29  Total Deaths per Million     18001 non-null  float64
 30  Total Deaths per 100rb       18001 non-null  float64
 31  Case Fatality Rate           18001 non-null  object
 32  Case Recovered Rate          18001 non-null  object
 33  Growth Factor of New Cases   16938 non-null  float64
 34  Growth Factor of New Deaths  15911 non-null  float64
dtypes: datetime64[ns](1), float64(13), int64(12), object(9)
memory usage: 4.8+ MB

# Data Processing

In [ ]:
# data covid
data_covid = data_covid.loc[data_covid['Province'] != 'Indonesia']
data_covid.describe()

,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,Total Active Cases,Total Regencies,Total_Cities,...,Population Density,Longitude,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Growth Factor of New Cases,Growth Factor of New Deaths
count,17469.000000,17469.000000,17469.000000,17469.000000,17469.000000,17469.000000,17469.000000,17469.000000,17469.000000,17469.000000,...,17469.000000,17469.000000,17468.000000,17468.000000,17468.000000,17468.000000,17468.000000,17468.000000,16409.000000,15382.000000
mean,221.715038,6.820539,193.815158,21.079341,27142.793062,788.823459,23163.196978,3190.772626,12.242372,2.960902,...,766.652970,113.670176,-2.790933,31.459612,3744.835133,0.819859,90.552603,9.055191,1.449956,1.085859
std,719.264533,26.958145,730.333716,444.126025,72894.566542,2100.638633,64903.050299,8569.973523,7.374481,2.360152,...,2789.740273,10.004733,3.647130,74.678681,6561.550622,2.320768,133.961572,13.396188,3.387755,1.695000
min,0.000000,0.000000,0.000000,-15797.000000,1.000000,0.000000,0.000000,-2343.000000,1.000000,1.000000,...,8.590000,96.910522,-8.682205,0.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.000000,0.000000,3.000000,-8.000000,879.000000,26.000000,483.000000,186.000000,7.000000,1.000000,...,47.790000,106.109004,-6.204699,1.950000,226.795000,0.000000,6.090000,0.610000,0.630000,0.620000
50%,42.000000,1.000000,27.000000,2.000000,6531.000000,165.000000,5034.000000,917.000000,11.000000,2.000000,...,103.840000,112.732941,-2.993595,8.845000,1728.155000,0.160000,52.100000,5.210000,1.000000,1.000000
75%,142.000000,4.000000,118.000000,34.000000,19517.000000,574.000000,15525.000000,2452.000000,15.000000,4.000000,...,262.700000,121.201093,0.212037,27.700000,4450.370000,0.740000,111.482500,11.150000,1.350000,1.000000
max,14622.000000,545.000000,20602.000000,9537.000000,840959.000000,25812.000000,818842.000000,117967.000000,29.000000,9.000000,...,16334.310000,138.696030,4.225615,1348.130000,77535.290000,63.800000,1272.450000,127.250000,175.000000,134.500000

# simpan data

In [ ]:
from google.colab import files
data_covid.to_csv('Data_covid_indonesia.csv', index=False)
files.download('Data_covid_indonesia.csv')